service: fastify-server

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1  # Change to your desired region

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: '{proxy+}'
          method: any

plugins:
  - serverless-offline