name: Deploy Fastify to AWS Lambda

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # Specify your Node.js version

      - name: Install dependencies
        run: yarn install

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Modify this to your desired AWS region

      - name: Package Lambda function
        run: |
          mkdir -p package
          cp -r * package/
          cd package
          zip -r ../function.zip .
          cd ..

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name YOUR_LAMBDA_FUNCTION_NAME --zip-file fileb://function.zip